### ISSUE TITLE
Make a table presenting for each kind of activity the different ways it can be externally implemented

### ISSUE THREAD

**Issue by olvegam** [BPMN-sw-evol/BPbSw-Traceability#13]
This list allows to know all the ways in Camunda for implementing an activity with external software.  This table is necessary for the thesis document and for any artifact to communicate how the BP-based traceability framework works.

**Comment by danilonunezgil** [comment]
![Image](https://github.com/BPMN-sw-evol/BPbSw-Traceability/assets/44626183/c2a77b16-5178-4f93-a33c-40128212d75d)
